### ISSUE TITLE
An item with the same key has already been added - GET(by id)

### ISSUE THREAD

**Issue by SayliS** [Elders/Cronus.Projections.Cassandra#1]
Hello, 

I am running into exception when querying data. https://gyazo.com/846cb6e8bd6f7c7b88c9eb60e0ffe230

This happens only the first time after application launch.

Additional information: I am trying to get same data (by same ID) twice in very short period of time.

Am I doing anything wrong here?

@mynkow

**Comment by sdluxeon** [comment]
Its a race condition. The Repo object is not thread safe. Two threads are trying to get items at the same time.

**Comment by sdluxeon** [comment]
You can log the stack

**Comment by mynkow** [comment]
You have to create a new instance of the repository every time you use it.
